# Generated by Django 5.0.7 on 2024-07-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
