# Generated by Django 5.0.7 on 2024-07-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_digital_orderitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
